#!/bin/sh 
#
# buildit
# Script for building Xorg tree for Solaris
#
###########################################################################
#
# Copyright 2006 Sun Microsystems, Inc.  All rights reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, and/or sell copies of the Software, and to permit persons
# to whom the Software is furnished to do so, provided that the above
# copyright notice(s) and this permission notice appear in all copies of
# the Software and that both the above copyright notice(s) and this
# permission notice appear in supporting documentation.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
# OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT
# OF THIRD PARTY RIGHTS. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
# HOLDERS INCLUDED IN THIS NOTICE BE LIABLE FOR ANY CLAIM, OR ANY SPECIAL
# INDIRECT OR CONSEQUENTIAL DAMAGES, OR ANY DAMAGES WHATSOEVER RESULTING
# FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT,
# NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION
# WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#
# Except as contained in this notice, the name of a copyright holder
# shall not be used in advertising or otherwise to promote the sale, use
# or other dealings in this Software without prior written authorization
# of the copyright holder.
#
###########################################################################
#
# ident "@(#)buildit 1.12     06/03/28 SMI"
#


CLOBBER=0
MAKE_PKGS=0

set -- `getopt cp $*`
if [ $? != 0 ]
then
    echo USAGE: $0 [-c]
    exit 2
fi

for i in $* ; do 
    case $i in
	-c)     CLOBBER=1; shift;;
	-p)     MAKE_PKGS=1; shift;;
    esac
done


# Add /opt/sfw/bin to path for GNU tools for external modules
PATH=$PATH:/opt/sfw/bin
export PATH

if [ $CLOBBER = 0 ] ; then
    for b in 32 64 ; do
	if [ -d build_$b ] ; then
	    cmp -s other_masters build_$b/.master_srcs
	    if [ $? != 0 ] ; then 
		echo "Master sources changed since last build of build_$b"
		echo "A 'clobber' build will be needed to remove and rebuild"  
		echo "the build directories.   Save any files you need from the"
		echo "build directories and then run $0 with the -c option."
		exit 1
	    fi
	fi
    done
fi

[ -d log ] || mkdir log

# Append all further output & errors to the log file
exec > log/buildit-XW 2>&1

echo "------------------------------------------------------------------------------"
echo "Start time: "
date
START=`perl -e 'print time'`
echo "Building on: "
uname -a
echo "Using this compiler: "
which cc
cc -V

if [ $CLOBBER = 1 ] ; then
    /bin/rm -rf unpacked build
fi

chmod +x build_src_tree

MACH=`uname -p`

for b in 32 64 ; do

    if [ $CLOBBER = 1 ] ; then
	/bin/rm -rf build_$b
    else
	if [ "$MACH" = "i386" ]; then
	    /bin/rm -rf build_$b/proto-i386-svr4
	else
	    /bin/rm -rf build_$b/proto-sun4-svr4
	fi
    fi

    
    ./build_src_tree -d build_$b

    cd build_$b

    cd xc
    if [ $b = 64 ] ; then
	BOOTSTRAPCFLAGS="-xarch=generic64"
    fi
    make -e -k World BOOTSTRAPCFLAGS=$BOOTSTRAPCFLAGS
    #make -k install.ln
    make -k install
    make -k install.man
    cd ..

    cd ..
done

echo ""
date
echo "\nFinished building the X.org Foundation tree for Solaris.\n"
echo ""
echo "Finish time: "
date
perl -e '$runtime=time-$ARGV[0];printf("Runtime: %d:%02d\n", $runtime/3600, ($runtime%3600)/60); ' $START

if [ $MAKE_PKGS = 1 ] ; then
    ./make_release_packages
fi
