###############################################################################
#
# Copyright (c) 2006, 2017, Oracle and/or its affiliates. All rights reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice (including the next
# paragraph) shall be included in all copies or substantial portions of the
# Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.
#
#

# Package name used in tarballs
MODULE_NAME=videoproto

# Version number (used in path names)
MODULE_VERSION=2.3.3

# Checksums for upstream tarball
TARBALL_MD5   = fe86de8ea3eb53b5a8f52956c5cd3174 
TARBALL_SHA1  = 4556b5c2243a2ca290ea2140dc1a427c4bac8ba2
TARBALL_SHA256= c7803889fd08e6fcaf7b68cc394fb038b2325d1f315e571a6954577e07cca702

# Patches to apply to source after unpacking, in order
SOURCE_PATCHES=	

# Package metadata
MODULE_DESC = headers & documentation for XVideo extension to the X11 protocol

### Include common rulesets
include ../Makefile.inc
