###############################################################################
#
# Copyright (c) 2006, 2012, Oracle and/or its affiliates. All rights reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice (including the next
# paragraph) shall be included in all copies or substantial portions of the
# Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.
#
#

# Package name used in tarballs
MODULE_NAME=xextproto

# Version number (used in path names)
MODULE_VERSION=7.2.1

# Checksums for upstream tarball
TARBALL_MD5   = eaac343af094e6b608cf15cfba0f77c5
TARBALL_SHA1  = f969e02009adf2d51fd1ba4583a859984728a461
TARBALL_SHA256= 7c53b105407ef3b2eb180a361bd672c1814524a600166a0a7dbbe76b97556d1a

# Patches to apply to source after unpacking, in order
SOURCE_PATCHES=	

# ARC cases that covered this module
# PSARC/2011/213 X Synchronization Extension version 3.1
MODULE_ARC_CASES = PSARC/2011/213

### Include common rulesets
include ../Makefile.inc
