###############################################################################
#
# Copyright (c) 2015, Oracle and/or its affiliates. All rights reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice (including the next
# paragraph) shall be included in all copies or substantial portions of the
# Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.
#

# Package name used in tarballs
MODULE_NAME=dri3proto

# Version number (used in path names)
MODULE_VERSION=1.0

# Checksums for upstream tarball
TARBALL_MD5  = a3d2cbe60a9ca1bf3aea6c93c817fee3
TARBALL_SHA1 = 1007eaa2f83022653a224f7d2e676ea51cba2f2b
TARBALL_SHA256 = 01be49d70200518b9a6b297131f6cc71f4ea2de17436896af153226a774fc074

# Patches to apply to source after unpacking, in order
SOURCE_PATCHES=	

# ARC cases that covered this module
# PSARC/2015/251 Xorg server 1.17
MODULE_ARC_CASES = PSARC/2015/251

# Package metadata
MODULE_DESC = headers for DRI3 extension to the X11 protocol

### Include common rulesets
include ../Makefile.inc
