###############################################################################
#
# Copyright (c) 2006, 2015, Oracle and/or its affiliates. All rights reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice (including the next
# paragraph) shall be included in all copies or substantial portions of the
# Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.
#
#

# Package name used in tarballs
MODULE_NAME=fontsproto

# Version number (used in path names)
MODULE_VERSION=2.1.3

# Checksums for upstream tarball
TARBALL_MD5   = 36934d00b00555eaacde9f091f392f97
TARBALL_SHA1  = 28c108bd6438c332122c10871c1fc6415591755f
TARBALL_SHA256= 259046b0dd9130825c4a4c479ba3591d6d0f17a33f54e294b56478729a6e5ab8

# Patches to apply to source after unpacking, in order
SOURCE_PATCHES=	symbol.patch,-p1

# Package metadata
MODULE_DESC = headers & documentation for font support in the X Window System

### Include common rulesets
include ../Makefile.inc
