# -*- Makefile -*- rules common to most X.Org TrueType font modules
#
# Copyright 2010 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice (including the next
# paragraph) shall be included in all copies or substantial portions of the
# Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.
#
#

# No configure script to run
CONFIGURE_TARGETS=
CONFIGURE_TARGETS_SET=yes

# Nothing to build
BUILD_TARGETS=
BUILD_TARGETS_SET=yes

# What to install
INSTALL_TARGETS=install_ttf $(MODULE_ADD_INSTALL_TARGETS)
INSTALL_TARGETS_SET=yes

### Include common rulesets
include ../Makefile.inc

# Set default directory name if not set in module makefile
TTF_SUBDIR_DEFAULT	= $(TTF_SUBDIR_SET:yes=$(POUND_SIGN))
$(TTF_SUBDIR_DEFAULT)	TTF_SUBDIR=$(MODULE_NAME)

TTF_FONT_DIR_DEFAULT	= $(TTF_FONT_DIR_SET:yes=$(POUND_SIGN))
$(TTF_FONT_DIR_DEFAULT)	TTF_FONT_DIR=$(TRUETYPE_FONT_DIR)/$(TTF_SUBDIR)

FONT_DEST_DIR=$(PROTODIR)/$(TTF_FONT_DIR)

install_ttf: $(SOURCE_TARGETS)
	-rm -rf $(FONT_DEST_DIR)
	mkdir -p $(FONT_DEST_DIR)
	cp $(TTF_FONT_FILES:%=$(SOURCE_DIR)/%) $(FONT_DEST_DIR)
	LD_LIBRARY_PATH="$(FONT_LIBS_PATH)" $(MKFONTSCALE) $(FONT_DEST_DIR)
	LD_LIBRARY_PATH="$(FONT_LIBS_PATH)" $(MKFONTDIR) $(FONT_DEST_DIR)



