# -*- Makefile -*- rules common to most X.Org TrueType font modules
#
# Copyright 2009 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, and/or sell copies of the Software, and to permit persons
# to whom the Software is furnished to do so, provided that the above
# copyright notice(s) and this permission notice appear in all copies of
# the Software and that both the above copyright notice(s) and this
# permission notice appear in supporting documentation.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
# OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT
# OF THIRD PARTY RIGHTS. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
# HOLDERS INCLUDED IN THIS NOTICE BE LIABLE FOR ANY CLAIM, OR ANY SPECIAL
# INDIRECT OR CONSEQUENTIAL DAMAGES, OR ANY DAMAGES WHATSOEVER RESULTING
# FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT,
# NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION
# WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
# 
# Except as contained in this notice, the name of a copyright holder
# shall not be used in advertising or otherwise to promote the sale, use
# or other dealings in this Software without prior written authorization
# of the copyright holder.
#
# ident	"@(#)Makefile.ttf	1.1	09/11/23 SMI"
#

# No configure script to run
CONFIGURE_TARGETS=
CONFIGURE_TARGETS_SET=yes

# Nothing to build
BUILD_TARGETS=
BUILD_TARGETS_SET=yes

# What to install
INSTALL_TARGETS=install_ttf $(MODULE_ADD_INSTALL_TARGETS)
INSTALL_TARGETS_SET=yes

### Include common rulesets
include ../Makefile.inc

# Set default directory name if not set in module makefile
TTF_SUBDIR_DEFAULT	= $(TTF_SUBDIR_SET:yes=$(POUND_SIGN))
$(TTF_SUBDIR_DEFAULT)	TTF_SUBDIR=$(MODULE_NAME)

TTF_FONT_DIR_DEFAULT	= $(TTF_FONT_DIR_SET:yes=$(POUND_SIGN))
$(TTF_FONT_DIR_DEFAULT)	TTF_FONT_DIR=$(TRUETYPE_FONT_DIR)/$(TTF_SUBDIR)

FONT_DEST_DIR=$(PROTODIR)/$(TTF_FONT_DIR)

install_ttf:: $(SOURCE_TARGETS)
	-rm -rf $(FONT_DEST_DIR)
	mkdir -p $(FONT_DEST_DIR)
	cp $(TTF_FONT_FILES:%=$(SOURCE_DIR)/%) $(FONT_DEST_DIR)
	$(MKFONTSCALE) $(FONT_DEST_DIR)
	$(MKFONTDIR) $(FONT_DEST_DIR)



