# -*- Makefile -*- rules common to most X.Org TrueType font modules
#
# Copyright (c) 2009, 2010, Oracle and/or its affiliates. All rights reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice (including the next
# paragraph) shall be included in all copies or substantial portions of the
# Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.
#
#

# No configure script to run
CONFIGURE_TARGETS=
CONFIGURE_TARGETS_SET=yes

# "Build" is just creating fonts.scale & fonts.dir metadata files
BUILD_TARGETS=build_ttf_dir
BUILD_TARGETS_SET=yes

# What to install
INSTALL_TARGETS=install_ttf $(MODULE_ADD_INSTALL_TARGETS)
INSTALL_TARGETS_SET=yes

### Include common rulesets
include ../Makefile.inc

# Set default directory name if not set in module makefile
TTF_SUBDIR_DEFAULT	= $(TTF_SUBDIR_SET:yes=$(POUND_SIGN))
$(TTF_SUBDIR_DEFAULT)	TTF_SUBDIR=$(MODULE_NAME)

TTF_FONT_DIR_DEFAULT	= $(TTF_FONT_DIR_SET:yes=$(POUND_SIGN))
$(TTF_FONT_DIR_DEFAULT)	TTF_FONT_DIR=$(TRUETYPE_FONT_DIR)/$(TTF_SUBDIR)

FONT_DEST_DIR=$(PROTODIR)/$(TTF_FONT_DIR)

SOURCE_FONT_FILES=$(TTF_FONT_FILES:%=$(SOURCE_DIR)/%)

FONT_DATA_FILES=fonts.dir fonts.scale
SOURCE_DATA_DIR=$(SOURCE_DIR)/$(TTF_SOURCE_SUBDIR)

SOURCE_FONT_DATA=$(FONT_DATA_FILES:%=$(SOURCE_DATA_DIR)%)

$(SOURCE_FONT_FILES): $(SOURCE_TARGETS)

$(SOURCE_DATA_DIR)fonts.scale: $(SOURCE_FONT_FILES)
	LD_LIBRARY_PATH="$(FONT_LIBS_PATH)" $(MKFONTSCALE) $(SOURCE_DATA_DIR)

$(SOURCE_DATA_DIR)fonts.dir: $(SOURCE_FONT_FILES) $(SOURCE_DATA_DIR)fonts.scale
	LD_LIBRARY_PATH="$(FONT_LIBS_PATH)" $(MKFONTDIR) $(SOURCE_DATA_DIR)

build_ttf_dir: $(SOURCE_DATA_DIR)fonts.dir

install_ttf: $(BUILD_TARGETS)
	-rm -rf $(FONT_DEST_DIR)
	mkdir -p $(FONT_DEST_DIR)
	cp -pf $(SOURCE_FONT_FILES) $(FONT_DEST_DIR)
	cp -pf $(SOURCE_FONT_DATA) $(FONT_DEST_DIR)

