.\" Copyright (c) 1989, 2008, Oracle and/or its affiliates. All rights reserved.
.\"
.\" Permission is hereby granted, free of charge, to any person obtaining a
.\" copy of this software and associated documentation files (the "Software"),
.\" to deal in the Software without restriction, including without limitation
.\" the rights to use, copy, modify, merge, publish, distribute, sublicense,
.\" and/or sell copies of the Software, and to permit persons to whom the
.\" Software is furnished to do so, subject to the following conditions:
.\"
.\" The above copyright notice and this permission notice (including the next
.\" paragraph) shall be included in all copies or substantial portions of the
.\" Software.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
.\" IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
.\" FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
.\" THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
.\" LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
.\" FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
.\" DEALINGS IN THE SOFTWARE.
.TH xlswins 1 "23 March 1992"
.IX "xlswins" "" "\f3xlswins\f1(1) \(em X window listing utility" ""
.IX "window" "list" "window" "listing utility \(em \f3xlswins\f1(1)" ""
.SH NAME
xlswins \- server window list displayer for X
.SH SYNOPSIS
.B xlswins
[-options ...]
.RI [ \ windowid\ ... ]
.SH DESCRIPTION
.B xlswins
lists the window tree.  By default, the root window is used as the starting
point, although a specific window may be specified using the \fI-id\fP option.
If no specific windows are given on the command line, the root window will be
used.
.SH "OPTIONS"
.PP
.TP 8
.B \-display \fIdisplayname\fP
This option specifies the X server to contact.
.TP 8
.B \-l
This option indicates that a long listing should be generated for each window.
This includes a number indicating the depth, the geometry relative to the 
parent as well as the location relative to the root window.
.TP 8
.B \-format \fIradix\fP
This option specifies the radix to use when printing out window ids.  Allowable
values are:  \fIhex\fP, \fIoctal\fP, and \fIdecimal\fP.  The default is hex.
.TP 8
.B \-indent \fInumber\fP
This option specifies the number of spaces that should be indented for each
level in the window tree.  The default is 2.
.PP
.SH "SEE ALSO"
.BR xprop (1),
.BR xwininfo (1)
.SH ENVIRONMENT
.TP 8
.B DISPLAY
to get the default host and display to use.
.SH BUGS
This should be integrated with xwininfo somehow.
.SH COPYRIGHT
Copyright 1988, Massachusetts Institute of Technology.
.br
See
.BR X11 (7)
for a full statement of rights and permissions.
.SH AUTHOR
Jim Fulton, MIT X Consortium
