###############################################################################
#
# transset utility for setting window transparency properties
#
# Copyright (c) 2009, 2012, Oracle and/or its affiliates. All rights reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice (including the next
# paragraph) shall be included in all copies or substantial portions of the
# Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.
#
#

# Package name used in tarballs
MODULE_NAME=transset

# Version number (used in path names)
MODULE_VERSION=1.0.0

# Checksums for upstream tarball
TARBALL_MD5   = 1aac8670c17803e30885eb5911f68d3d
TARBALL_SHA1  = 583fc57eecbb4558127805093af8cc46ec677cdd
TARBALL_SHA256= 19ee2525c4044743c49a95e43716bc3bd1dddf527e47585ee118e650b83a7e8f

# Man pages to apply Sun footer to & attributes to list
SUNTOUCHED_MANPAGES = man/transset.man
MODULE_STABILITY=Volatile

include ../Makefile.inc
