###############################################################################
#
# Xlib-based client library for Distributed Multihead X (DMX) extension
#
# Copyright (c) 2010, 2014, Oracle and/or its affiliates. All rights reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice (including the next
# paragraph) shall be included in all copies or substantial portions of the
# Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.
#
#

# Package name used in tarballs
MODULE_NAME=libdmx

# Version number (used in path names)
MODULE_VERSION=1.1.3

# Checksums for upstream tarball
TARBALL_MD5   = ba983eba5a9f05d152a0725b8e863151
TARBALL_SHA1  = 0eeac14a06cffb04a1c78793563f233a8f8b79be
TARBALL_SHA256= c97da36d2e56a2d7b6e4f896241785acc95e97eb9557465fd66ba2a155a7b201

# Patches to apply to source after unpacking, in order
SOURCE_PATCHES = 

# Package metadata
ORACLE_TPNO = 14484
ORACLE_TPNO_SET	= yes

# Library name (used for specfiles/mapfiles)
LIBNAME=dmx

# Man pages to apply Sun footer to & attributes to list
SUNTOUCHED_MANPAGES=man/*.man
MODULE_STABILITY=Volatile
LIB_MAN_SUFFIX=3dmx

# pkg-config files to update
FIX_PC_FILES=dmx.pc.in

include ../Makefile.inc
