###############################################################################
#
# Copyright (c) 2006, 2013, Oracle and/or its affiliates. All rights reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice (including the next
# paragraph) shall be included in all copies or substantial portions of the
# Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.
#
#

# Package name used in tarballs
MODULE_NAME=inputproto

# Version number (used in path names)
MODULE_VERSION=2.3

# Checksums for upstream tarball
TARBALL_MD5   = 94db391e60044e140c9854203d080654
TARBALL_SHA1  = 4eacc1883593d3f0040e410be3afc8483c7d2409
TARBALL_SHA256= 7d26b193f6699f8e9c1e28bf026844b7ecea33dd644402523471be109152c32f

# Patches to apply to source after unpacking, in order
SOURCE_PATCHES= 

# Package metadata
MODULE_DESC = headers & documentation for XInputExtension extension to the X11 protocol

### Include common rulesets
include ../Makefile.inc
